
name: TemplateRepo  # Set to null to use the repository name

tagline: "Python Projects Perfected: Innovate, Develop, and Deploy Effortlessly!"

description: >-
  PyPackIT is a free and open-source toolkit 
  <b>empowering the development of open-source Python projects on GitHub</b>.
  It is a <b>dynamic repository template</b> that provides a complete, professional, and 
  robust infrastructure for your project, where the only thing missing is your code.
  With PyPackIT, you can solely focus on what truly matters: 
  implementing your ideas and bringing your vision to life! 

key_points:

  - title: Automation
    description: >-
      PyPackIT streamlines a remarkable portion of the process of creating, 
      documenting, testing, publishing, and maintaining Python packages, 
      making your project development a pleasant breeze!

  - title: Synchronization
    description: >-
      PyPackIT gathers all your project's key information and configuration in one place, 
      and dynamically updates them throughout your repository, Python package, and documentation website.

  - title: Configuration
    description: >-
      PyPackIT elevates your project by providing full configuration for your repository, 
      Python package, and documentation website, according to the latest guidelines and best practices.

  - title: Customization
    description: >-
      While carefully configured, PyPackIT is also fully customizable, 
      allowing you to tailor every aspect of your development pipeline to your specific needs.

  - title: Documentation
    description: >-
      PyPackIT comes with a professional website for your project, that is easily
      customizable, and automatically generated and deployed on your preferred platform.

  - title: Production
    description: >-
      With PyPackIT, the only remaining step to publishing a production-ready
      Python project is adding your code, unit-tests and documentation content. 

keywords:
  - python
  - github
  - packaging
  - template
  - dynamic repository
  - repository template
  - documentation
  - testing
  - deployment
  - maintenance
  - automation
  - development
  - infrastructure
  - streamline

trove_classifiers:
  - "Typing :: Typed"
  - "Natural Language :: English"

license:
  id: GNU_AGPL_v3+

start_year: 2023

repo:
  full_name: "aariam/templaterepo"

authors:
  - aariam

# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files
funding:
  github: aariam
