
name: TemplateRepo  # Set to null to use the repository name

tagline: "Python Projects Perfected: Innovate, Develop, and Deploy Effortlessly!"

description: >-
  PyPackIT is a free and open-source toolkit 
  **empowering the development of open-source Python projects on GitHub**.
  It is a **dynamic repository template** that provides a complete, professional, and 
  robust infrastructure for your project, where the only thing missing is your code.
  With PyPackIT, you can solely focus on what truly matters: 
  implementing your ideas and bringing your vision to life! 

keywords:
  - python
  - github
  - packaging
  - template
  - dynamic repository
  - repository template
  - documentation
  - testing
  - deployment
  - maintenance
  - automation
  - development
  - infrastructure
  - streamline

trove_classifiers:
  - "Typing :: Typed"
  - "Natural Language :: English"

license:
  id: GNU_AGPL_v3+

start_year: 2023

repo:
  full_name: "aariam/templaterepo"

authors:
  - aariam

# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files
funding:
  github: aariam


