# GitHub configuration file for displaying a sponsor button in the repository.

# References:
#  GitHub Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: armin-ariamajd