# ReadTheDocs configuration file
# ReadTheDocs uses this configuration to build the website on readthedocs.io.
# Reference: https://docs.readthedocs.io/en/stable/config-file/v2.html


# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_checkout:
      - git fetch --unshallow

# Install dependencies
conda:
  environment: requirements/dev/doc.yaml

# Install the package
python:
   install:
     - method: pip
       path: .

# Build documentation with Sphinx
sphinx:
   configuration: docs/source/conf.py
   builder: dirhtml
   fail_on_warning: false

# Build all additional formats of the documentation, i.e. pdf, epub, and htmlzip
formats: all


