#
#
#
#
#


[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]
namespaces = false


[tool.versioningit]


[tool.versioningit.vcs]
method = "git"
match = ["v*"]

[tool.versioningit.next-version]
method = "smallest-release"

[tool.versioningit.format]
# The format used by versioneer
# Ref: https://versioningit.readthedocs.io/en/stable/index.html#example-configurations
distance = "{next_version}.dev{distance}"
dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"
distance-dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"

[tool.versioningit.onbuild]
method = "replace-version"
require-match = true
replacement = """dict(
    version="{version}",
    version_tuple={version_tuple},
    build_date="{build_date:%Y.%m.%d}",
    branch="{branch}",
    distance="{distance}",
    head_commit_hash="{revision}",
    vcs_name="{vcs_name}"
)"""
source-file = "template_package/__init__.py"
build-file = "template_package/__init__.py"


[project]
dynamic = ["version"]
name = "template-package--test.2...see"
readme = {file = "README.md", content-type = "text/markdown"}
