#
#
#
#
#


[build-system]
requires = ["setuptools>=61.0", "versioningit"]
build-backend = "setuptools.build_meta"


[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]
namespaces = false


[tool.versioningit]


[tool.versioningit.vcs]
method = "git"
match = ["v*"]

[tool.versioningit.format]
# The format used by versioneer
# Ref: https://versioningit.readthedocs.io/en/stable/index.html#example-configurations
distance = "{base_version}+{distance}.{vcs}{rev}"
dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"
distance-dirty = "{base_version}+{distance}.{vcs}{rev}.dirty"

[tool.versioningit.onbuild]
method = "replace-version"
require-match = true
source-file = "template_package/__init__.py"
build-file = "template_package/__init__.py"


[project]
dynamic = ["version"]
name = "template_package"
readme = {file = "README.md", content-type = "text/markdown"}
