name: pypackit_dev

channels:
  - conda-forge
  - defaults

dependencies:

  # Base
  - python = 3.11
  - pip

  - requests >= 2.31.0, < 3
  - ruamel.yaml >= 0.17.32, < 0.18
  - tomlkit >= 0.11.8, < 0.12
  - trove-classifiers