# Configuration file for the `tj-actions/changed-files@v37` action.

# IMPORTANT: DO NOT USE UNDERSCORES ('_') IN KEYS.

github:
  - '.github/**/*.yaml'
  - '.github/**/*.yml'
package:
  - 'src/**'
  - 'pyproject.toml'
  - 'setup.py'
  - 'MANIFEST.in'
  - '!**/README.md'
docs:
  - 'docs/website/source/**'
  - 'src/**/*.py'
  - 'meta/metadata/*.yaml'
dev:
  - 'dev/repodynamics/**'
meta:
  - 'meta/**'
tests:
  - 'tests/**/*.py'
