# Environment for the documentation

name: docs_env

channels:
  - conda-forge
  - defaults

dependencies:

  # Base
  - python
  - pip

  # Documentation
  - sphinx
  - pydata-sphinx-theme
  - myst-parser
  - sphinx-design
  - sphinx-copybutton
  - ablog
  - librsvg  # for including SVG files in PDF build (done by latexmk)
  - sphinxext-opengraph

  # Metadata
  - requests >= 2.31.0, < 3
  - ruamel.yaml >= 0.17.32, < 0.18

  # Pip-only dependencies
  - pip:
    # Documentation
    - sphinx-last-updated-by-git
    - sphinxcontrib-svg2pdfconverter
