

name: '🖥 App  🪲 Bug Report  🧑‍💻 API'
description: >-
  Report a problem encountered while using the application, such as unexpected results and errors.

labels: ["Bug: App", "Status: Triage"]
assignees:
  - aariam

body:
  
  - type: markdown
    attributes:
      value: >-
        Thank you for taking the time to report a problem in {metadata[project][name]}; 
        we greatly appreciate your contribution! ❤️🙏
        
        ## Guidelines
        
        ### 🚨 Choosing the right form
        
        <p align="justify">
        Please note that this form is specifically for reporting a <b>non-security-related bug</b> 
        in the {metadata[project][name]} API, i.e. an unexpected behavior that occurs
        while using the application, either as an import package, a command-line tool,
        or via a GUI. 
        
        
        For <b>reporting a security vulnerability</b>, please first read our
        <a href="{metadata[urls][github][security][policy]}">security policy</a>, and then
        fill a <a href="{metadata[urls][github][security][new_advisory]}">private security advisory form</a> 
        instead. 
        For other types of issues, such as 
        <a href="{metadata[urls][github][issues][new][app_bug_setup]}">problems during setup</a>,
        </p>
        
        
        ### ⚠️ Verifying the bug
        
        Before submitting a report, please verify that:
        
        1. The issue you are experiencing is in fact a bug, 
        and not a documented expected behavior.
        
        2. The bug is reproducible in the latest version of the software, 
        and has not yet been reported.
        
        <blockquote>
            💡 <a href="{}"><b>Open a discussion instead!</b></a>
            <br>
            This verification process is non-trivial, and can be time-consuming.
            If you are not a collaborator and don't have the time to go through the process, 
            you can always open a discussion instead; we will investigate the problem as soon as possible, 
            and convert the discussion into an issue if the bug is verified.
        </blockquote>
        
        <details>

  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: >-
        Please make sure that you are following our 
        [Bug Report Guidelines](https://github.com/Armin-Ariamajd/TemplateRepo/blob/main/docs/CONTRIBUTING.md#how-to-contribute-changes),
        so that we can process the issue as soon as possible.

      options:

        - label: >-
            I have read the [Contributing Guidelines]() and am following the [Bug Report Guidelines]().
          required: true

        - label: >-
            I have read, understood, and agree to follow the [Code of Conduct](https://github.com/Armin-Ariamajd/TemplateRepo/blob/main/docs/CODE_OF_CONDUCT.md).
          required: true


  - type: markdown
    attributes:
      value: |
        </details>
        <br>
        
        ## System and Version Specifications

  - type: dropdown
    id: package_version
    attributes:
      label: Package Version
      description: |
        Which versions of our software are affected? 
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true


  - type: dropdown
    id: python_version
    attributes:
      label: Python Version
      description: |
        Which Python versions have you tested? 
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - 3.11
        - 3.10
        - 3.9


  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: |
        Which operating systems have you tested? 
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows


  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true


  - type: textarea
    id: code
    attributes:
      label: Example
      description: Please provide the most minimal possible example to reproduce the bug.
      placeholder: "import pypackit"
      value: "import pypackit"
      render: python
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell


  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  

