name: 'Get Metadata'
description: 'Get Metadata JSON file.'
inputs:
  json_filepath:
    description: "Path to the JSON file to read."
    default: "metadata.json"
    required: false
    type: string
outputs:
  json:
    description: "JSON file content as a string."
    value: ${{steps.get_json_file.outputs.json_file}}

runs:
  using: 'composite'
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Print JSON File (for debugging)
      shell: bash
      run: cat ./metadata.json
    - name: Parse JSON File
      id: get_json_file
      shell: bash
      run: |
        echo "json_file=$(python dev/utils.py ${{inputs.json_filepath}})" >> $GITHUB_OUTPUT
      # cat_results=$(python3 -c 'import json; f = open({{inputs.json_filepath}}); print(json.dumps(json.load(f))); f.close()')
      # echo "parsed_json_file=${cat_results}" >> $GITHUB_OUTPUT
