root: index
defaults:
  hidden: true
entries:
- file: intro/index
  title: Intro
  options:
    numbered: true
  entries:
  - file: intro/overview/index
  - file: intro/background/index
  - file: intro/glossary/index
  - file: intro/references/index
  - file: intro/supplementary/index
    entries:
    - file: intro/supplementary/python/index
    - file: intro/supplementary/versioning/index
    - file: intro/supplementary/indexes/index
    - file: intro/supplementary/publication/index
- file: manual/index
  title: Manual
  options:
    numbered: true
  entries:
  - file: manual/install/index
    entries:
    - file: manual/install/new/index
    - file: manual/install/existing/index
    - file: manual/install/upgrade/index
    - file: manual/install/common/index
  - file: manual/quickstart/index
  - file: manual/testing/index
- file: news/index
  title: News
  entries:
  - glob: news/post/**
- file: contribute/index
  title: Contribute
  options:
    numbered: true
- file: about/index
  title: About
  options:
    numbered: true
  entries:
  - file: about/contact/index
- file: help/index
  title: Help
  options:
    numbered: true
  entries:
  - file: help/sitemap/index
