# Runtime dependencies of the package.

development_status: 1


operating_systems:

    - id: windows
      cibuilds: null  # https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip

    - id: macos
      cibuilds: null

    - id: linux
      cibuilds: null


python_version_min: "3.9"


# Array of tables
dependencies:

  - name: numpy
    used_for: |
      Numerical computing.
    url_source: ""
    url_homepage: ""
    url_docs: ""
    pip_spec: "numpy >= 1.21.2"
    conda:
      channel: null
      spec: null


# Table of arrays of tables
optional_dependencies: null


# Table
scripts: null


# Table
gui_scripts: null


# Table of tables
entry_points: null


