name: '[Callable]: Project Manager'
on:
  workflow_call:
#    inputs:
#      meta-sync:
#        type: string
#        default: report
#        required: false
#        description: |
#          The action to take when the dynamic files are out of sync with the repository meta content.
#          Selecting 'none' will disable this action.
#      hooks:
#        type: string
#        default: report
#        required: false
#        description: |
#          The action to take when running the workflow hooks.
#          Selecting 'none' will disable this action.
#      package-build:
#        type: boolean
#        required: false
#        default: false
#        description: |
#          Build the package and upload the builds as artifacts.
#      package-lint:
#        type: boolean
#        required: false
#        default: false
#        description: |
#          Run the linting workflow.
#      package-test:
#        type: boolean
#        required: false
#        default: false
#        description: |
#          Run the test workflow on package.
#      website-build:
#        type: boolean
#        required: false
#        default: false
#        description: |
#          Build the documentation with Sphinx and upload the builds as artifacts.
#      first-major-release:
#        type: boolean
#        required: false
#        default: false
#        description: |
#          Release the current 0.X.Y version as the first major release.
    secrets:
      repo-admin-token:
        description: Token with admin permissions to the repository.
        required: false
      zenodo-token:
        description: Token for Zenodo API.
        required: false
    outputs:
      run:
        value: ${{ jobs.manager.outputs.run }}
        description: Whether to run subsequent jobs.
      web-build:
        value: ${{ jobs.manager.outputs.web-build }}
        description: Configurations for website job.
      web-deploy:
        value: ${{ jobs.manager.outputs.web-deploy }}
        description: Configurations for website deployment job.
      lint:
        value: ${{ jobs.manager.outputs.lint }}
        description: Configurations for lint job.
      test:
        value: ${{ jobs.manager.outputs.test }}
        description: Configurations for test job.
      build:
        value: ${{ jobs.manager.outputs.build }}
        description: Configurations for build job.
      publish-testpypi:
        value: ${{ jobs.manager.outputs.publish-testpypi }}
        description: Configurations for publish-testpypi job.
      test-testpypi:
        value: ${{ jobs.manager.outputs.test-testpypi }}
        description: Configurations for test-testpypi job.
      publish-pypi:
        value: ${{ jobs.manager.outputs.publish-pypi }}
        description: Configurations for publish-pypi job.
      test-pypi:
        value: ${{ jobs.manager.outputs.test-pypi }}
        description: Configurations for test-pypi job.
      release:
        value: ${{ jobs.manager.outputs.release }}
        description: Configurations for release job.
jobs:
  manager:
    name: 'Manager'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      fail: ${{ steps.proman.outputs.fail }}
      run: ${{ steps.proman.outputs.run }}
      web-build: ${{ steps.proman.outputs.web-build }}
      web-deploy: ${{ steps.proman.outputs.web-deploy }}
      lint: ${{ steps.proman.outputs.lint }}
      test: ${{ steps.proman.outputs.test }}
      build: ${{ steps.proman.outputs.build }}
      publish-testpypi: ${{ steps.proman.outputs.publish-testpypi }}
      test-testpypi: ${{ steps.proman.outputs.test-testpypi }}
      publish-pypi: ${{ steps.proman.outputs.publish-pypi }}
      test-pypi: ${{ steps.proman.outputs.test-pypi }}
      release: ${{ steps.proman.outputs.release }}
    steps:
      - name: 'Project Manager'
        id: proman
        uses: RepoDynamics/ProMan@v1
        with:
          admin-token: ${{ secrets.repo-admin-token }}
          zenodo-token: ${{ secrets.zenodo-token }}
  status:
    name: 'Status'
    runs-on: ubuntu-latest
    needs: manager
    steps:
      - name: 'Status Check'
        run: |
          if [ "${{ needs.manager.outputs.fail }}" = "true" ]; then
            exit 1
          else
            exit 0
          fi
