# Continuous Integration pipeline

name: CI/CD
run-name: 'CI/CD: Triggered on ${{github.ref}} by ${{github.event_name}}'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened


jobs:

  metadata:
    name: 'Load repository metadata'
    uses: ./.github/workflows/repo_meta.yaml

  changes:
    name: 'Get changed files'
    uses: ./.github/workflows/repo_files_change.yaml


  package:
    name: 'Test package'
    needs: [changes, metadata]
    if: ${{ !failure() && needs.changes.outputs.package == 'true' }}
    uses: ./.github/workflows/package_ci.yaml
    permissions:
      pull-requests: write
      security-events: write
      actions: read
      contents: read
    with:
      metadata: ${{needs.metadata.outputs.json}}
      checkout-ref: ${{ github.head_ref }}
      base-ref: ${{ github.base_ref }}
      head-ref: ${{ github.head_ref }}


  docs:
    name: 'Build documentation with Sphinx'
    needs: [changes]
    if: ${{ !failure() && needs.changes.outputs.docs == 'true' }}
    uses: ./.github/workflows/docs_build.yaml
    with:
      checkout-ref: ${{ github.head_ref }}


  publish-testpypi:
    name: 'Publish on TestPyPI'
    needs: [package]
#    if: |
#      always() &&
#      needs.build-package.result == 'success' &&
#      needs.test-local.result == 'success' &&
#      github.event_name == 'push' &&
#      github.ref == 'refs/heads/main'
    uses: ./.github/workflows/package_release_pypi.yaml
    permissions:
      id-token: write
    with:
      package-name: ${{ needs.build-package.outputs.package-name }}
      package-version: ${{ needs.build-package.outputs.package-version }}
      artifact-name: ${{ needs.build-package.outputs.artifact-name }}
      platform-name: 'testpypi'


  wait-for-testpypi:
    # Wait for 5 min before running the next job, to make sure package is registered at TestPyPI
    name: 'Wait for TestPyPI'
    needs: publish-testpypi
#    if: |
#      always() &&
#      needs.publish-testpypi.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: 'Waiting ...'
        run: sleep 300s


  test-testpypi:
    name: 'Install and test from TestPyPI'
    needs: [ metadata, package, wait-for-testpypi ]
#    if: |
#      always() &&
#      needs.publish-testpypi.result == 'success'
    uses: ./.github/workflows/package_test.yaml
    with:
      metadata: ${{ needs.metadata.outputs.json }}
      install-source: "testpypi"
      install-version: ${{ needs.package.outputs.package-version }}
