# Continuous Integration pipeline

name: "[On Push]: CI"
run-name: 'CI: ${{github.ref}}'

on: push


jobs:

  context:
    name: 'Workflow Run / context'
    # Generate output summary of the workflow run context.
    # This job outputs a sanitized version of the `github` context of the workflow run
    # as job summary, for the purpose of logging and debugging.
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout script'
        uses: actions/checkout@v3
        with:
          sparse-checkout: .github/scripts/context_summary.py
          sparse-checkout-cone-mode: false

      - name: 'Generate context summary'
        run: python '.github/scripts/context_summary.py'
        env:
          GH_CONTEXT: ${{ toJson(github) }}


  changes:
    name: 'Repository Files'
    # Get all changed files in the repository and the groups they belong to.
    uses: ./.github/workflows/repo_changes.yaml


  metadata:
    name: 'Repository Metadata'
    uses: ./.github/workflows/repo_meta.yaml


  sync:
    name: 'Repository Files'
    needs: changes
    if: fromJSON(needs.changes.outputs.json).meta.any_modified == 'true'
    uses: ./.github/workflows/repo_sync.yaml
    permissions:
      contents: write


  settings:
    name: 'Repository Settings'
    needs: [metadata, changes]
    if: |
      github.ref == 'refs/heads/main' &&
      fromJSON(needs.metadata.outputs.json).config.update_repo_settings == true &&
      fromJSON(needs.changes.outputs.json).meta.any_modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: 'Update repository info'
        # https://octokit.github.io/rest.js/v19
        # https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28
        uses: actions/github-script@v6
        env:
          REPO_NAME: ${{ fromJSON(needs.metadata.outputs.json).project.name }}
          REPO_DESCRIPTION: ${{ fromJSON(needs.metadata.outputs.json).project.tagline }}
          REPO_HOMEPAGE: ${{ fromJSON(needs.metadata.outputs.json).url.website.home }}
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          script: |
            const { REPO_NAME, REPO_DESCRIPTION, REPO_HOMEPAGE } = process.env
            github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: REPO_NAME,
              description: REPO_DESCRIPTION,
              homepage: REPO_HOMEPAGE,
              has_issues: true,
              has_wiki: false,
              default_branch: 'main',
              allow_squash_merge: true,
              squash_merge_commit_title: 'PR_TITLE',
              squash_merge_commit_message: 'PR_BODY',
              allow_merge_commit: true,
              merge_commit_title: 'PR_TITLE',
              merge_commit_message: 'PR_BODY',
              allow_update_branch: true,
              delete_branch_on_merge: true,
              security_and_analysis: {secret_scanning: {status: 'enabled'}},
              security_and_analysis: {secret_scanning_push_protection: {status: 'enabled'}},
            })
            github.rest.repos.replaceAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
              names: ${{ toJSON(fromJSON(needs.metadata.outputs.json).project.keywords_slugs) }},
            })
            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                checks: [
                  {context: 'test-package'},
                ]
              },
              enforce_admins: null,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1,
                require_last_push_approval: true,
              },
              restrictions: null,
              required_linear_history: true,
              allow_force_pushes: false,
              allow_deletions: false,
              required_conversation_resolution: true,
              lock_branch: false,
              allow_fork_syncing: true,
            })


  package:
    name: 'Test package'
    needs: [metadata, changes, sync]
    if: ${{ !failure() && fromJSON(needs.changes.outputs.json).package.any_modified == 'true' }}
    uses: ./.github/workflows/package_ci.yaml
    permissions:
      pull-requests: write
      security-events: write
      actions: read
      contents: read
    with:
      metadata: ${{needs.metadata.outputs.json}}
      checkout-ref: ${{ github.ref_name }}
      base-ref: ${{ github.event.before }}
      head-ref: ${{ needs.sync.outputs.commit-hash || github.event.after }}


  docs:
    name: 'Build documentation with Sphinx'
    needs: [changes, sync]
    if: ${{ !failure() && fromJSON(needs.changes.outputs.json).docs.any_modified == 'true' }}
    uses: ./.github/workflows/docs_build.yaml
    with:
      checkout-ref: ${{ github.ref_name }}
