# Continuous Integration pipeline

name: CI
run-name: 'CI: Triggered on ${{github.ref}}'

on: push


jobs:

  intro:
    name: 'Intro Summary'
    runs-on: ubuntu-latest
    steps:
      - name: 'Output summary'
        env:
          GH_CONTEXT: ${{ toJson(github) }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "GH_CONT<<$EOF" >> "$GITHUB_ENV"
          echo "$('$GH_CONTEXT')" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
      - run: |
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>🖥 github context</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          echo '${{ env.GH_CONT }}' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>🖥 event payload</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json" >> $GITHUB_STEP_SUMMARY
          cat ${{github.event_path}} >> "$GITHUB_STEP_SUMMARY"
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          
    

  metadata:
    name: 'Load repository metadata'
    uses: ./.github/workflows/repo_meta.yaml

  changes:
    name: 'Get changed files'
    uses: ./.github/workflows/repo_files_change.yaml

  sync:
    name: 'Sync files'
    needs: changes
    if: needs.changes.outputs.meta == 'true'
    uses: ./.github/workflows/repo_sync.yaml
    permissions:
      contents: write

  package:
    name: 'Test package'
    needs: [metadata, changes, sync]
    if: ${{ !failure() && needs.changes.outputs.package == 'true' }}
    uses: ./.github/workflows/package_ci.yaml
    permissions:
      pull-requests: write
      security-events: write
      actions: read
      contents: read
    with:
      metadata: ${{needs.metadata.outputs.json}}
      checkout-ref: ${{ github.ref_name }}
      base-ref: ${{ github.event.before }}
      head-ref: ${{ needs.sync.outputs.commit-hash || github.event.after }}

  docs:
    name: 'Build documentation with Sphinx'
    needs: [changes, sync]
    if: ${{ !failure() && needs.changes.outputs.docs == 'true' }}
    uses: ./.github/workflows/docs_build.yaml
    with:
      checkout-ref: ${{ github.ref_name }}
