

name: "Issues: Format Opened Issue"
run-name: 'Issues: format opened issue'

on: issues


jobs:

  opened:
    name: 'Format opened issue'
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Format the issue body'
        id: format
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "BODY<<$EOF" >> "$GITHUB_ENV"
          echo "$(python dev/repodynamics/src/pypackit/format_issue.py '$ISSUE_BODY')" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

      - name: Update issue
        # https://github.com/marketplace/actions/issues-helper
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.BODY }}
          update-mode: 'replace'

      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Add some comments.
