# Generate a distribution package for PyPI.
# Publish the package on PyPI or TestPyPI.
# This reusable workflow uses the [pypi-publish](https://github.com/pypa/gh-action-pypi-publish) GitHub Action
# to publish the distribution package on either PyPI or TestPyPI, depending on the input.

name: '[Callable]: Package - Build'

on:
  workflow_call:
    inputs:
      config:
        description: Configuration as a JSON string.
        type: string
        required: true
#      ref:
#        type: string
#        default: ''
#        required: false
#        description: |
#          Reference (i.e. branch, tag or SHA) of the current repository to checkout,
#          i.e. the `ref` input of `actions/checkout`.
#      repository:
#        type: string
#        default: ${{ github.repository }}
#        required: false
#        description: |
#          Repository to checkout, i.e. the `repository` input of `actions/checkout`.
#      metadata:
#        type: string
#        required: true
#        description: |
#          CI metadata as a JSON string.

jobs:

  build-pure:
    name: Pure Python Distribution
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ fromJSON(inputs.config).repository }}
          ref: ${{ fromJSON(inputs.config).ref }}
          fetch-depth: 0
          path: repo
      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Environment Setup
        shell: bash
        run: |
          echo "::group::Requirements Installation"
          python -m pip install --upgrade pip build twine readme-renderer[md]
          echo "::endgroup::"
          echo "::group::Environment Overview"
          python3 -c "import sys; print(sys.version)"
          python3 -m pip list
          echo "::endgroup::"
          echo "::group::Latest Git Tag"
          git -C repo describe
          echo "::endgroup::"

      - name: Build
        shell: bash
        env:
          PURE_PYTHON: ${{ fromJSON(inputs.config).pure-python }}
          PKG_PATH: ${{ fromJSON(inputs.config).path-pkg }}
        run: |
          if $PURE_PYTHON; then
            echo "::group::Build & Source Distribution"
            python -m build ./repo/$PKG_PATH --outdir ./build/dist
            echo "::endgroup::"
          else
            echo "::group::Source Distribution"
            python -m build ./repo/$PKG_PATH --outdir ./build/dist --sdist
            echo "::endgroup::"
          fi
      - name: PyPI README Render
        shell: bash
        run: >-
          python -m readme_renderer
          './repo/${{ fromJSON(inputs.config).path-readme }}'
          --output ./build/README.html
      - name: PyPI README Check
        # https://twine.readthedocs.io/en/stable/#twine-check
        # https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup
        run: twine check ./build/dist/*
      - name: Build Upload
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          path: ./build
          name: ${{ fromJSON(inputs.config).artifact-name }}

  build-native:
    name: Native Binary Distribution - ${{ matrix.os }}
    if: fromJSON(inputs.config).pure-python == false
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(inputs.config).cibw-matrix-platform }}
        py-ver: ${{ fromJSON(inputs.config).cibw-matrix-python }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ fromJSON(inputs.config).repository }}
          fetch-depth: 0
          ref: ${{ fromJSON(inputs.config).ref }}
          path: repo
      - name: Build
        # https://cibuildwheel.readthedocs.io/en/stable/
        # https://github.com/pypa/cibuildwheel
        uses: pypa/cibuildwheel@v2.16
        with:
          package-dir: ./repo/${{ fromJSON(inputs.config).path-pkg }}
          output-dir: build/dist
        env:
          CIBW_BUILD: ${{ matrix.py-ver }}-${{ matrix.platform.cibw_platform }}
          CIBW_BUILD_VERBOSITY: 2
      - name: Build Upload
        uses: actions/upload-artifact@v4
        with:
          path: ./build
          name: ${{ fromJSON(inputs.config).artifact-name }} (${{ matrix.platform }})
