name: '[Callable]: Package - Publish'

on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true
        description: Configuration as a JSON string.
#      download-url:
#        type: string
#        required: true
#        description: |
#          Expected URL of the specific package version on the indexing platform.
#      upload-url:
#        type: string
#        required: true
#        description: |
#          URL of the package index to upload to.
#      platform:
#        type: string
#        default: 'TestPyPI'
#        required: false
#        description: |
#          Platform to publish to; either 'TestPyPI' (default) or 'PyPI'.

jobs:
  deploy-pypi:
    name: ${{ fromJSON(inputs.config).env-name }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ fromJSON(inputs.config).env-name }}
      url: ${{ fromJSON(inputs.config).env-url }}
    permissions:
      id-token: write
    steps:
      - name: Artifact Download
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Artifact Processing
        env:
          ARTIFACT_NAMES: ${{ fromJSON(inputs.config).build-artifact-names }}
        shell: python
        run: |
          import json
          import os
          import shutil
          from pathlib import Path
          
          artifact_names = json.loads(os.getenv('ARTIFACT_NAMES'))
          
          root_dist_path = Path('dist')
          root_dist_path.mkdir()
          
          for artifact_name in artifact_names:
              artifact_dist_path = Path('artifacts') / artifact_name / 'dist'              
              if artifact_dist_path.is_dir():
                  print(f"Moving contents of {artifact_dist_path} to root dist directory")                  
                  for item in artifact_dist_path.iterdir():
                      destination = root_dist_path / item.name
                      if item.is_dir():
                          shutil.copytree(item, destination, dirs_exist_ok=True)
                      else:
                          shutil.copy2(item, destination)
              else:
                  print(f"Directory {artifact_dist_path} does not exist, skipping")
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        # https://github.com/marketplace/actions/pypi-publish
        with:
          packages-dir: dist
          repository-url: ${{ fromJSON(inputs.config).index-url }}
          verify-metadata: true
          verbose: true
          print-hash: true
          skip-existing: false
          attestations: false  # Unstable at the moment.
