name: '[Reusable]: GitHub Container Release'

on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true
        description: Configuration as a JSON string.

jobs:
  publish:
    name: ${{ matrix.task.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ fromJSON(inputs.config).ref }}
          fetch-depth: 0
          path: ${{ fromJSON(inputs.config).repo-path }}
      - name: Release
        uses: aariam/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
          IMAGE_NAME: ${{ github.repository }}
          LATEST_TAG_OFF: ${{ fromJSON(inputs.config).latest-tag }}
          ADDITIONAL_TAG: ${{ fromJSON(inputs.config).version }}
          PUBLIC_REGISTRY_CHECK: yes
          REPO2DOCKER_EXTRA_ARGS: >-
            ${{ fromJSON(inputs.config).args }}
            --label org.opencontainers.image.source=https://github.com/${{ github.repository }}
            
