name: "[A]: Expire Announcement"

on:

  workflow_dispatch:

jobs:

  metadata:
    name: 'Load repository metadata'
    uses: ./.github/workflows/repo_get-metadata.yaml

  expire:
    name: 'Make announcement'
    needs: metadata
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repository from ${{ github.ref }}'
        uses: actions/checkout@v3

      - name: 'Display announcement'
        run: |
          last_commit_date=$(git log -1 --format=%cd --date=unix ${{ fromJSON(needs.metadata.outputs.json).paths.website_sphinx_announcement }})
          echo $last_commit_date
          current_date=$(date --utc +%s)
          echo $current_date
          echo $((current_date - last_commit_date))
#          if [ $time_difference -gt $duration ]; then
#              echo "true"
#          else
#              echo "false"
#          fi
#      - name: 'Update announcement file'
#        run: echo "${{ github.event.inputs.announcement }}" > ${{ fromJSON(needs.metadata.outputs.json).paths.website_sphinx_announcement }}
#
#      - name: 'Commit changes and push'
#        # https://github.com/marketplace/actions/git-auto-commit
#        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          file_pattern: ${{ fromJSON(needs.metadata.outputs.json).paths.website_sphinx_announcement }}
#          commit_message: >-
#            docs(announcement): update announcement for ${{ inputs.trigger }}
#          commit_user_name: RepoDynamics[bot]
#
#      - name: 'Create job summary'
#        if: always()
#        run: |
#          echo "Following announcement was published ${{ (github.event_name == 'workflow_dispatch' && format('{0} {1}', 'manually by', github.actor)) || format('{0} {1}', 'automatically for', inputs.trigger) }}:" >> $GITHUB_STEP_SUMMARY
#          echo "\`\`\`html" >> $GITHUB_STEP_SUMMARY
#          echo "${{ inputs.announcement }}" >> "$GITHUB_STEP_SUMMARY"
#          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY