name: "1. [C/D]: Make Announcement"
run-name: Make announcement by ${{ github.event_name == "workflow_dispatch" }} ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      announcement:
        description: "Announcement message"
        required: true
        type: string
        default: >-
          <i class="fa-solid fa-triangle-exclamation"></i> 
          The project is under active development and not yet fully implemented.


jobs:

  announcement:
    runs-on: ubuntu-latest
    steps:

      - name: Display announcement
        run: echo "${{ github.event.inputs.announcement }}"

