name: "1. [C/D]: Make Announcement"
run-name: "Make Announcement: ${{ format('Triggered {0} by {1}.', (github.event_name == 'workflow_dispatch' && 'manually') || 'automatically', (github.event_name == 'workflow_dispatch' && github.actor) || github.event.inputs.trigger) }}"

on:
  workflow_call:
    inputs:
      announcement:
        description: "Announcement message"
        required: true
        type: string
      trigger:
        description: "Trigger type"
        required: true
        type: string

  workflow_dispatch:
    inputs:
      announcement:
        description: "Announcement message"
        required: true
        type: string
        default: >-
          <i class="fa-solid fa-triangle-exclamation"></i> 
          The project is under active development and not yet fully implemented.


jobs:

  announcement:
    runs-on: ubuntu-latest
    steps:

      - name: Display announcement
        run: echo "${{ github.event.inputs.announcement }}"

