# Get all files that have been modified during an event (e.g. push, pull request).
#
# This is a callable-only workflow, which uses the `tj-actions/changed-files` action
# to detect all files that have been modified during an event (e.g. push, pull request),
# and outputs them as a JSON string.
#
# The keys of the JSON dictionary are the groups that the files belong to,
# defined in `.github/config/changed_files.yaml`. Another key is `all`, which is added as extra
# (i.e. without being defined in the config file), which contains details on changes in the entire repository.
# Each value is then a dictionary itself, as defined in the action's documentation.
#
# References:
# - https://github.com/marketplace/actions/changed-files


name: "[On Call]: get changed files"

on:
  workflow_call:
    outputs:
      json:
        value: ${{ jobs.changes.outputs.json }}


jobs:

  changes:
    name: 'changes'
    outputs:
      json: ${{ steps.output.outputs.json }}
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get all changed files'
        # https://github.com/marketplace/actions/changed-files
        uses: tj-actions/changed-files@v37
        id: all

      - name: 'Get changed groups'
        uses: tj-actions/changed-files@v37
        id: groups
        with:
          files_yaml_from_source_file: .github/config/changed_files.yaml

      - name: 'Output'
        id: output
        run: python '.github/scripts/changed_files.py'
        env:
          GROUPS: ${{ toJson(steps.groups.outputs) }}
          ALL: ${{ toJson(steps.all.outputs) }}
