name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
#  release:
#    types: [published]
#  schedule:
#    # Weekly tests run on main by default:
#    #   Scheduled workflows run on the latest commit on the default or base branch.
#    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
#    - cron: '0 0 * * *'

jobs:

  changed_files:
    runs-on: ubuntu-latest
    name: 'Get changed files'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get all test, doc and src files that have changed
        id: changed
        uses: tj-actions/changed-files@v37

      - name: Verify the contents of the .github/outputs/added_files.json file
        run: echo "${{ steps.changed.outputs.all_changed_and_modified_files }}"