name: CI
on:
  workflow_dispatch:
  push:
  pull_request:
#  release:
#    types: [published]
#  schedule:
#    # Weekly tests run on main by default:
#    #   Scheduled workflows run on the latest commit on the default or base branch.
#    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
#    - cron: '0 0 * * *'

jobs:

  changed_files:
    runs-on: ubuntu-latest
    name: 'Get changed files'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get all test, doc and src files that have changed
        id: all
        uses: tj-actions/changed-files@v37

      - name: Get all test, doc and src files that have changed
        id: groups
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            
            docs:
              - 'docs/website/source/**'
              - 'src/**/*.py'
              - 'meta/metadata/*.yaml'
            
            package:
              - 'src/**'
              - 'tests/**/*.py'
              - 'pyproject.toml'
              - 'setup.py'
            
            meta:
              - 'meta/**'
            
            workflows:
              - '.github/workflows/*.yaml'
            

      - name: Verify the contents of the .github/outputs/added_files.json file
        run: |
          echo "${{ steps.all.outputs.all_changed_and_modified_files }}"
          echo "${{ steps.groups.outputs.docs_any_changed }}"
          echo "${{ steps.groups.outputs.package_any_changed }}"
          echo "${{ steps.groups.outputs.workflows_any_changed }}"
          


      - name: 'Create summary'
        run: |
          echo "#### 🏁 Results" >> $GITHUB_STEP_SUMMARY
          echo "- **Package**: ${{ (steps.groups.outputs.package_any_changed == 'true' && '✅') || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Docs**: ${{ (steps.groups.outputs.docs_any_changed == 'true' && '✅') || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Workflows**: ${{ (steps.groups.outputs.workflows_any_changed == 'true' && '✅') || '❌' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Meta**: ${{ (steps.groups.outputs.meta_any_changed == 'true' && '✅') || '❌' }}" >> $GITHUB_STEP_SUMMARY
          
          echo "#### 📝 Changed files" >> $GITHUB_STEP_SUMMARY
          for file in ${{ steps.all.outputs.all_changed_and_modified_files }}; do
            echo "- `$file`" >> $GITHUB_STEP_SUMMARY
          done