# Continuous Integration pipeline

name: CI/CD
run-name: 'CI/CD: Triggered by ${{github.event_name}} at ${{github.ref}}'

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'

jobs:

  echo_git:
    name: echo github
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{toJson(github)}}"

  local-test:
    name: 'Install and test from ${{github.ref}}'
    uses: ./.github/workflows/package_test.yaml
    with:
      install-source: "local"

  