# Build the documentation with Sphinx and upload the builds as artifacts.

name: 'Docs - Build'
run-name: 'Docs - Build'

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays at 00:00 UTC

defaults:
  run:
    shell: micromamba-shell {0}


jobs:

  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup environment'
        # https://github.com/mamba-org/setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: requirements/dev/doc.yaml
          generate-run-shell: true
          init-shell: bash

      # To make PDF output, we need the latexmk package and some other plugins, which are not available via conda.
      - name: 'Install extra requirements'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk
          sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra tex-gyre

      - name: 'Install package'
        run: python -m pip install .

      - name: 'Display conda environment'
        run: micromamba list

      - name: 'Display pip environment'
        run: pip list

      - name: 'Display non-Python packages'
        run: |
          echo "latexmk Version:"
          latexmk --version
          echo "rsvg Version:"
          rsvg-convert --version

      - name: 'Display directory tree'
        shell: bash -el {0}
        run: ls -a

      - name: 'Build HTML'
        if: always()
        run: |
          cd docs
          make clean html

      - name: 'Build LaTeX'
        if: always()
        # Use `make latex` instead of `make latexpdf` to be able to pass extra arguments to `latexmk` in next step.
        run: |
          cd docs
          make latex

      - name: 'Build PDF'
        if: always()
        # latexmk docs: https://ctan.mc1.root.project-creative.net/support/latexmk/latexmk.pdf
        run : |
          cd docs/_build/latex
          LATEXMKOPTS="-outdir=./pdf -auxdir=./aux -bibfudge- -makeindexfudge-" make 

      - name: 'Upload builds'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: docs/_build/*
          name: sphinx-build

      - name: 'Upload PDF'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: docs/_build/latex/pdf/*.pdf
          name: pdf

      - name: 'Upload GitHub Pages artifact'
        # https://github.com/actions/upload-pages-artifact
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/_build/html'
