

name: "Issues - Format"
run-name: 'Issues: Format submitted issue'

on:
  issues:
    types: [opened]

jobs:

  format-issue:
    name: 'Format issue'
    runs-on: ubuntu-latest
    outputs:
      formatted-issue-body: ${{ steps.format.outputs.body }}
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Format the issue body'
        id: format
        run: echo "body=$(python meta/scripts/format_issue.py '${{ github.event.issue.body }}')" >> "$GITHUB_OUTPUT"

  format:
    runs-on: ubuntu-latest
    needs: format-issue
    permissions:
      issues: write
    steps:
      - name: Update issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          issue-number: ${{ github.event.issue.number }}
          body: ${{ needs.format-issue.outputs.formatted-issue-body }}
          update-mode: 'replace'