

name: "Issues - Format"
run-name: 'Issues: Format submitted issue'

on:
  issues:
    types: [opened]

jobs:


  format:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Format the issue body'
        id: format
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "ISSUE_BODY<<$EOF" >> "$GITHUB_ENV"
          echo "$(python meta/scripts/format_issue.py '${{ github.event.issue.body }}')" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

      - name: Update issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          issue-number: ${{ github.event.issue.number }}
          body: ${{ env.ISSUE_BODY }}
          update-mode: 'replace'