name: Get Metadata
run-name: Get Metadata
on: 
  workflow_call:
    outputs:
      package_name:
        description: "Name of the package"
        value: ${{ jobs.get_json.outputs.json_file }}

jobs:
  get_json:
    name: Load JSON File
    runs-on: ubuntu-latest
    outputs:
      json_file: ${{ steps.get_json_file.outputs.json_file }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Print JSON File (for debugging)
        run: cat ./metadata.json
      - name: Parse JSON File
        id: get_json_file
        run: |
          cat_results=$(python3 -c 'import json; f = open("metadata.json"); print(json.dumps(json.load(f))); f.close()')
          echo "$cat_results"
          echo "json_file=${cat_results}" >> $GITHUB_OUTPUT
