name: Get Metadata
run-name: Get Metadata
on: 
  workflow_call:
    outputs:
      package_name:
        description: "Name of the package"
        value: ${{ jobs.get_json.outputs.js }}
  

jobs:
  get_json:
    name: Load JSON File
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - run: cat ./metadata.json
      - name: Get Matrix data
        id: get_matrix
        run: |
          cat_results=$(python3 -c 'import json; f = open("metadata.json"); print(json.dumps(json.load(f))); f.close()')
          echo "$cat_results"
          echo "matrix=${cat_results}" >> $GITHUB_OUTPUT
