# Continuous Integration pipeline

name: 1. Publish GH Pages

on:
  workflow_dispatch:


jobs:

  build-docs:
    name: 'Build documentation with Sphinx'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/test-tag',
              sha: context.sha
            })

      - name: 'Checkout repository from ${{github.ref}}'
        uses: actions/checkout@v3
        with:
          ref: 'refs/tags/test-tag'
