# Sync labels in the repository.

# This workflow runs every time there is a change to the config file at '.github/config/labels.yaml'
#  and automatically syncs all labels in the repository based on that configuration.

# References:
#  Uses: https://github.com/micnncim/action-label-syncer


name: 'Labels - Sync'
run-name: 'Labels: Sync'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/config/labels.yaml
      - .github/workflows/labels_sync.yaml


jobs:

  sync-labels:
    name: 'Sync'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Sync labels'
        # https://github.com/marketplace/actions/label-syncer
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/config/labels.yaml
          prune: true  # delete removed labels