# Build the ReadTheDocs website for pull-requests and add a link to the pull request's description.
# Note: Enable "Preview Documentation from Pull Requests" in ReadtheDocs project at https://docs.readthedocs.io/en/latest/pull-requests.html
# Ref: https://github.com/readthedocs/actions/tree/v1.1/preview

name: 'Docs - ReadTheDocs PR'
run-name: 'Docs: Build ReadTheDocs preview for ${{github.ref}}'

on:
  pull_request_target:
    types:
      - opened

jobs:

  load-metadata:
    name: 'Load repository metadata'
    uses: ./.github/workflows/repo_get-metadata.yaml
    with:
      branch: ${{ github.base_ref }}

  generate-docs:
    name: 'Generate preview'
    needs: load-metadata
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - run: echo "${{ github.event }}"

      - name: 'Build docs'
        uses: readthedocs/actions/preview@v1
        with:
          project-slug: ${{ fromJSON(needs.load-metadata.outputs.json).website.rtd_name }}