# Publish the package on PyPI or TestPyPI.
# This reusable workflow uses the [pypi-publish](https://github.com/pypa/gh-action-pypi-publish) GitHub Action
# to publish the distribution package on either PyPI or TestPyPI, depending on the input.


name: '[On Call]: Package - Publish PyPI'

on:
  workflow_call:
    inputs:
      platform-name:
        description: |
          Platform to publish to; either 'TestPyPI' (default) or 'PyPI'.
        type: string
        required: false
        default: 'TestPyPI'

      package-name:
        description: |
          Name of the package on (Test)PyPI.
          This is used to link the deployment to the package's page on (Test)PyPI.
        type: string
        required: true

      package-version:
        description: |
          Version of the package being deployed.
          This is used to link the deployment to the package's page on (Test)PyPI.
        type: string
        required: true

      artifact-name:
        description: |
          Name of the artifact containing the distribution package.
          The artifact must be uploaded in the caller workflow, prior to calling this workflow.
          It should contain a source distribution, and as many binary distributions as required.
        type: string
        required: false
        default: Distribution Package

jobs:

  package-release-pypi:
    name: "${{inputs.platform-name}} /"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.platform-name }}
      url: ${{ steps.script.outputs.download-url }}
    permissions:
      id-token: write
    steps:
      - name: 'Download sdist and wheels artifacts'
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: dist

      - name: 'Checkout script'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          sparse-checkout: .github/script/workflow.py
          sparse-checkout-cone-mode: false

      - name: 'Run script'
        id: script
        env:
          RD_PACKAGE_NAME: ${{ inputs.package-name }}
          RD_PACKAGE_VERSION: ${{ inputs.package-version }}
          RD_PLATFORM_NAME: ${{ inputs.platform-name }}
          RD_DIST_PATH: dist
        run: python .github/script/workflow.py

      - name: 'Upload package'
        uses: pypa/gh-action-pypi-publish@release/v1
        # https://github.com/marketplace/actions/pypi-publish
        with:
          packages-dir: dist
          repository-url: ${{ steps.script.outputs.upload-url }}
          verify-metadata: true
          verbose: true
          print-hash: true
          skip-existing: false
