# Publish the package on PyPI or TestPyPI.
# This reusable workflow uses the [pypi-publish](https://github.com/pypa/gh-action-pypi-publish) GitHub Action
# to publish the distribution package on either PyPI or TestPyPI, depending on the input.


name: 'Package - Publish PyPI'
run-name: >-
  'Package: Publish on ${{ fromJSON('{"pypi":"PyPI","testpypi":"TestPyPI"}')[inputs.platform] }}'
  'from ${{github.ref}}'

on:
  workflow_call:
    inputs:
      artifact-name:
        description: |
          Name of the artifact containing the distribution package.
          The artifact must be uploaded in the caller workflow, prior to calling this workflow.
          It should contain a source distribution, and as many binary distributions as required.
        required: true
        type: string

      package-name:
        description: |
          Name of the package on (Test)PyPI.
          This is used to link the deployment to the package's page on (Test)PyPI.
        required: true
        type: string

      platform-name:
        description: Platform to publish to; either 'testpypi' (default) or 'pypi'.
        required: false
        default: 'testpypi'
        type: string


jobs:

  display-inputs:
    name: 'Display workflow inputs'
    runs-on: ubuntu-latest
    steps:


  process-inputs:
    name: 'Process inputs'
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.environment.outputs.name }}
      env-url: ${{ steps.environment.outputs.url }}
      repo-url: ${{ steps.environment.outputs.repo-url }}
    steps:
      - name: 'Calculate deployment environment data'
        id: environment
        run: |
          echo "name=${{ fromJSON('{"pypi":"PyPI","testpypi":"TestPyPI"}')[inputs.platform] }}" >> $GITHUB_OUTPUT
          echo "url=${{ fromJSON(format('{{"pypi":"https://pypi.org/project/{0}","testpypi":"https://test.pypi.org/project/{1}"}}', inputs.package-name, inputs.package-name ))[inputs.platform] }}" >> $GITHUB_OUTPUT
          echo "repo-url=${{ fromJSON('{"pypi":"https://upload.pypi.org/legacy","testpypi":"https://test.pypi.org/legacy"}')[inputs.platform] }}" >> $GITHUB_OUTPUT
      - name: 'Generate summary'
        run: |
          echo "### Inputs:" >> $GITHUB_STEP_SUMMARY
          echo "- artifact-name: ${{inputs.artifact-name}}" >> $GITHUB_STEP_SUMMARY
          echo "- package-name: ${{inputs.package-name}}" >> $GITHUB_STEP_SUMMARY
          echo "- platform-name: ${{inputs.platform-name}}" >> $GITHUB_STEP_SUMMARY
          echo "### Outputs:" >> $GITHUB_STEP_SUMMARY
          echo "- environment-name: ${{ steps.environment.outputs.name }}" >> $GITHUB_STEP_SUMMARY
          echo "- environment-url: ${{ steps.environment.outputs.url }}" >> $GITHUB_STEP_SUMMARY
          echo "- repository-url: ${{ steps.environment.outputs.repo-url }}" >> $GITHUB_STEP_SUMMARY

      - name: 'Display inputs'
        run: |
          echo "::group::artifact-name"
          echo ${{inputs.artifact-name}}
          echo "::endgroup::"
          echo "::group::package-name"
          echo ${{inputs.package-name}}
          echo "::endgroup::"
          echo "::group::platform"
          echo ${{inputs.platform}}
          echo "::endgroup::"


      - name: 'Display deployment environment data'
        run: |
          echo "::group::name"
          echo ${{ steps.environment.outputs.name }}
          echo "::endgroup::"
          echo "::group::url"
          echo ${{ steps.environment.outputs.url }}
          echo "::endgroup::"
          echo "::group::repository-url"
          echo ${{ steps.environment.outputs.repo-url }}
          echo "::endgroup::"

  publish:
    name: 'Publish on ${{needs.process-inputs.outputs.env-name}}'
    needs: process-inputs
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.process-inputs.outputs.env-name }}
      url: ${{ needs.process-inputs.outputs.env-url }}
    permissions:
      id-token: write
    steps:
      - name: 'Download sdist and wheels artifacts'
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: dist

      - name: 'Display file tree'
        run: find .

      - name: 'Upload package to ${{needs.process-inputs.outputs.env-name}}'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ needs.process-inputs.outputs.repo-url }}
          verbose: true
          print-hash: true
          skip-existing: false
