# Publish the package on PyPI

name: 'Package - Publish - PyPI'
run-name: 'Package: Publish on PyPI from ${{github.ref}}'

on:
  workflow_call:


jobs:

  publish_pypi:
    name: 'Publish distribution to PyPI'
    needs: get_package
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/project/${{ needs.get_package.outputs.package_name }}
    permissions:
      id-token: write

    steps:
      - name: 'Download sdist and wheels artifacts'
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.get_package.outputs.artifact_name }}
          path: dist

      - name: 'Upload to PyPI'
        # https://github.com/pypa/gh-action-pypi-publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
