# Publish the package on PyPI or TestPyPI.

name: 'Package - Publish - PyPI'
run-name: 'Package: Publish on ${{inputs.platform}} from ${{github.ref}}'

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the artifact containing the distribution package."
        required: true
        type: string

      package-name:
        description: "Name of the package on TestPyPI."
        required: true
        type: string

      platform:
        description: "Platform to publish to; either 'pypi' or 'testpypi'."
        required: false
        default: 'testpypi'
        type: string


jobs:

  publish:
    name: 'Publish on ${{inputs.platform}}'
    runs-on: ubuntu-latest
    environment:
      name: ${{ fromJSON('{"pypi":"PyPI","testpypi":"TestPyPI"}')[inputs.platform] }}
      url: ${{ fromJSON('{"pypi":"https://pypi.org/project/${{ inputs.package-name }}","testpypi":"https://test.pypi.org/project/${{ inputs.package-name }}"}')[inputs.platform] }}

    permissions:
      id-token: write

    steps:
      - name: 'Display target environment'
        run: |
          echo ${{ fromJSON(format('{{"pypi":"https://pypi.org/project/{1}","testpypi":"https://test.pypi.org/project/{2}"}}', inputs.package-name, inputs.package-name ))[inputs.platform] }}
          echo ${{ fromJSON('{"pypi":"PyPI","testpypi":"TestPyPI"}')[inputs.platform] }}
      - name: 'Download sdist and wheels artifacts'
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: dist

      - name: 'Display file tree'
        run: find .

      - name: 'Upload to PyPI'
        # https://github.com/pypa/gh-action-pypi-publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true
#          skip-existing: true