# Publish the package on TestPyPI

name: 'Package - Publish - TestPyPI'
run-name: 'Package: Publish on TestPyPI from ${{github.ref_name}}'

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Name of the artifact containing the distribution package."
        required: true
        type: string

      package-name:
        description: "Name of the package on TestPyPI."
        required: true
        type: string


jobs:

  publish-testpypi:
    name: 'Publish distribution to TestPyPI'
    runs-on: ubuntu-latest
    environment:
      name: TestPyPI
      url: https://test.pypi.org/project/${{ inputs.package-name }}
    permissions:
      id-token: write

    steps:
      - name: 'Download sdist and wheels artifacts'
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: dist

      - name: 'Display file tree'
        run: find .

      - name: 'Upload to TestPyPI'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          print-hash: true
          skip-existing: true
