# Run static code analysis

name: Get Metadata
run-name: Get Metadata

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      json:
        description: 'Repository Metadata'
        value: ${{jobs.get-metadata.outputs.metadata}}


jobs:

  get-metadata:
    name: 'Load package metadata'
    outputs:
      metadata: ${{ steps.get-metadata.outputs.json }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Setup environment'
        # https://github.com/mamba-org/setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: repo/requirements.yaml
          cache-environment: true
          cache-environment-key: repo-dynamics
          generate-run-shell: true
          init-shell: bash

      - name: 'Get metadata'
        id: get-metadata
        shell: bash -el {0}
        run: echo "json=$(python repo/dynamics/metadata.py)" >> $GITHUB_OUTPUT

      - name: 'Display metadata'
        if: always()
        run: cat repo/metadata/metadata_full.json


      - name: 'Create summary'
        if: always()
        run: |
          echo "## Metadata" >> $GITHUB_STEP_SUMMARY
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>Metadata</summary>" >> $GITHUB_STEP_SUMMARY
          echo "<pre>" >> $GITHUB_STEP_SUMMARY
          echo "<code>" >> $GITHUB_STEP_SUMMARY
          cat repo/metadata/metadata_full.json >> "$GITHUB_STEP_SUMMARY"
          echo "</code>" >> $GITHUB_STEP_SUMMARY
          echo "</pre>" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
          
      - name: 'Upload metadata as artifact'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: repo/metadata/metadata_full.json
          name: 'metadata'
