# Run static code analysis

name: Get Metadata
run-name: Get Metadata

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      json:
        description: 'Repository Metadata'
        value: ${{jobs.get-metadata.outputs.metadata}}


jobs:

  get-metadata:
    name: 'Load package metadata'
    outputs:
      metadata: ${{ steps.get-metadata.outputs.json }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Setup environment'
        # https://github.com/mamba-org/setup-micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: repo/requirements.yaml
          generate-run-shell: true
          init-shell: bash

      - name: 'Get metadata'
        id: get-metadata
        shell: bash -el {0}
        run: echo "json=$(python repo/dynamics/metadata.py)" >> $GITHUB_OUTPUT

#      - name: 'Display metadata'
#        if: always()
#        run: echo "${{steps.get-metadata.outputs.json}} | python -m json.tool"
#
#      - name: 'Create summary'
#        if: always()
#        run: |
#          echo "## Metadata" >> $GITHUB_STEP_SUMMARY
#          echo "${{steps.get-metadata.outputs.json}} | python -m json.tool" >> $GITHUB_STEP_SUMMARY
