name: "Callable: Get Changed Files"
run-name: "Repo: Get changed files in ${{github.event_name}} event"

on:
  workflow_call:
    outputs:
      json:
        value: ${{ jobs.changes.outputs.json }}

jobs:

  changes:
    name: 'changes'
    outputs:
      json: ${{ steps.output.outputs.json }}
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get all changed files'
        # https://github.com/marketplace/actions/changed-files
        uses: tj-actions/changed-files@v37
        id: all

      - name: 'Get changed groups'
        uses: tj-actions/changed-files@v37
        id: groups
        with:
          files_yaml_from_source_file: .github/config/changed_files.yaml

      - name: 'Output'
        id: output
        run: python '.github/scripts/changed_files.py'
        env:
          GROUPS: ${{ toJson(steps.groups.outputs) }}
          ALL: ${{ toJson(steps.all.outputs) }}
