# Run static code analysis

name: Get Metadata
run-name: Get Metadata

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      json:
        description: 'Repository Metadata'
        value: ${{jobs.get-metadata.outputs.metadata}}


jobs:

  get-metadata:
    name: 'Load package metadata'
    outputs:
      metadata: ${{ steps.get_metadata.outputs.json }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      - name: 'Get metadata'
        id: get_metadata
        run: echo "json=$(python dev/repo_sync/read_metadata.py)" >> $GITHUB_OUTPUT

      - name: 'Display metadata'
        run: echo ${{needs.get-metadata.outputs.json}}
