name: Sync - Repo
run-name: 'Sync Repo: Triggered on ${{github.ref}} by ${{github.event_name}}'

on:
  workflow_dispatch:
  push:
  pull_request:


jobs:

  update:
    name: 'Update files'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: 'Update'
        run: python dev/repo_sync/sync_files.py

      - name: 'Commit and push'
        # https://github.com/marketplace/actions/git-auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'meta: sync dynamic files after metadata modification'
          commit_user_name: 'RepoSync[bot]'
