name: test

on:
  workflow_dispatch:

jobs:

  test-checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: meta/requirements.txt
          sparse-checkout-cone-mode: false
          persist-credentials: false
      - run: pwd
      - run: ls -la
      - run: ls -la $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          ref: 'announcement'
      - run: pwd
      - run: ls -la
      - run: ls -la $GITHUB_WORKSPACE

  test-location:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -la
      - run: find .
      - run: ls -la $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          sparse-checkout: meta/data
          sparse-checkout-cone-mode: false
          path: _repodynamics
      - run: pwd
      - run: ls -la
      - run: find .
      - run: ls -la $GITHUB_WORKSPACE
#      - uses: actions/upload-artifact@v3
#        with:
#          path: before.txt
#          name: 'docs'
#      - uses: actions/upload-artifact@v3
#        with:
#          path: after.txt
#          name: 'docs'

  test-meta:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: repodynamics/meta@main



#  tag:
#    name: 'Create tag'
#    runs-on: ubuntu-latest
#    permissions: write-all
#    steps:
#      - uses: actions/checkout@v3
#      - name: Tag and push current repo code
#        run: |
#          git config --global user.email ${{ github.actor }}@users.noreply.github.com
#          git config --global user.name ${{ github.actor }}
#          git tag -a "v0.0.7" -m "Release version 0.0.7"
#          git push origin "v0.0.5"
#
#      - name: 'Commit changes and push'
#        # https://github.com/marketplace/actions/git-auto-commit
#        uses: stefanzweifel/git-auto-commit-action@v4
#        id: commit
#        with:
#          commit_message: 'release: updating changelog'
#          commit_user_name: 'RepoDynamics[bot]'
#          tagging_message: "v0.0.6"


#  context:
#    runs-on: ubuntu-latest
#    name: 'Workflow Context /'
#    steps:
#      #      - uses: actions/checkout@v3
#      - name: 'Workflow Run Context'
#        uses: repodynamics/context@main
#
#      - name: 'Workflow Metadata'
#        uses: repodynamics/meta@main
