name: update-meta
run-name: Update metadata
on: [workflow_dispatch, push]
jobs:
  get_test_scope:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - run: cat ./badges_shields.json
      - name: Get Matrix data
        id: get_matrix
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "matrix<<${delimiter}" >> "${GITHUB_OUTPUT}"
          cat ./badges_shields.json >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$matrix"
          
          
    
  
  run_tests:
      needs: get_test_scope
      runs-on: ubuntu-latest
      steps:
        - name: print from next job
          run: | 
            echo "${{needs.get_test_scope.outputs.matrix && fromJson(needs.get_test_scope.outputs.matrix).style}}"

