# Run static code analysis

name: Lint Test
run-name: Lint Test

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:

  get_package_metadata:

    name: Get Package Metadata
    uses: ./.github/actions/get_metadata.yaml


  echo_metadata:

    name: Print Metadata Values
    needs: get_package_metadata
    runs-on: ubuntu-latest
    steps:
      - name: Complete JSON File
        run: echo ${{ needs.get_package_metadata.outputs.json_file }}

      - name: Package Name
        run: echo ${{ needs.get_package_metadata.outputs.package_name }}

      - name: Python Versions
        run: echo "${{ needs.get_package_metadata.outputs.python_versions }}"

      - name: Operating Systems
        run: echo "${{ needs.get_package_metadata.outputs.operating_systems }}"


  lint:

    name: Static Code Analysis
    needs: get_package_metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print System Info
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install Linters
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: requirements/dev/lint.yaml
          cache-environment: true

      - name: Print Environment
        shell: bash -el {0}
        run: micromamba list

      - name: PyLint
        if: always()
        shell: micromamba-shell {0}
        run: pylint ${{ needs.get_package_metadata.outputs.package_name }}

      - name: Black
        if: always()
        shell: micromamba-shell {0}
        run: black --check -l 99 ${{ needs.get_package_metadata.outputs.package_name }}

