name: update-meta
run-name: Update metadata
on: [workflow_dispatch, push]
jobs:
  get_test_scope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get Matrix data
        id: get_matrix
        run: |
          echo "matrix=$(python dev/utils.py)" >> $GITHUB_OUTPUT
    outputs:
      matrix: ${{ steps.get_matrix.outputs.matrix }}
  
  run_tests:
      needs: get_test_scope
      runs-on: ubuntu-latest
      steps:
        - name: print from next job
          run: echo ${{ needs.get_test_scope.outputs.matrix }}
