name: TT2
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch, push]
jobs:
  Run-My-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Script
        id: run_script
        run: |
          return_value=$(python dev/utils.py)
          echo "::set-output name=RETURN_VALUE::$return_value"

      - name: Use the return value
        run: echo "The return value is ${{ steps.run_script.outputs.RETURN_VALUE }}"
