# Run the test-suite of the Python package

name: Test Suite
run-name: Test Suite

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


jobs:

  get_package_metadata:
    name: Get Package Metadata
    uses: ./.github/workflows/get_metadata.yaml

  echo_metadata:
    name: Print Metadata Values
    needs: get_package_metadata
    runs-on: ubuntu-latest
    steps:
      - name: Complete JSON File
        run: echo ${{ needs.get_package_metadata.outputs.json_file }}

      - name: Package Name
        run: echo ${{ needs.get_package_metadata.outputs.package_name }}

      - name: Python Versions
        run: echo "${{ needs.get_package_metadata.outputs.python_versions }}"

      - name: Operating Systems
        run: echo "${{ needs.get_package_metadata.outputs.operating_systems }}"


  test_suite:
    name: Test (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    needs: get_package_metadata
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.get_package_metadata.outputs.operating_systems) }}
        python-version: ${{ fromJson(needs.get_package_metadata.outputs.python_versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print System Info
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install Test Dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: requirements/dev/test.yaml
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Display Python Version
        shell: micromamba-shell {0}
        run: python -c "import sys; print(sys.version)"

      - name: Update pip
        shell: micromamba-shell {0}
        run: python -m pip install --upgrade pip

      - name: Install Package
        shell: micromamba-shell {0}
        run: python -m pip install .

      - name: Print Installed Packages
        shell: micromamba-shell {0}
        run: python -m pip list