name: test

on:
  workflow_dispatch:

jobs:

  tag:
    name: 'Create tag'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Tag and push current repo code
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git tag -a "v0.0.4" -m "Release version 0.0.4"
          git push origin "v0.0.4"