name: update-meta
run-name: Update metadata
on: [workflow_dispatch, push]
jobs:
  get_test_scope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get Matrix data
        id: get_matrix
        run: |
          return_value=$(python dev/utils.py)
          echo "Obtained values: ${{ return_value }}"
          echo "::set-output name=matrix::$return_value"
    outputs:
      matrix: ${{ steps.get_matrix.outputs.matrix }}
  
  run_tests:
      needs: get_test_scope
      runs-on: ubuntu-latest
      steps:
        - name: print from next job
          run: echo ${{ needs.get_test_scope.outputs.matrix }}
