name: update-meta
run-name: Update metadata
on: [workflow_dispatch, push]
jobs:
  get_test_scope:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get_matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Get Matrix data
        id: get_matrix
        run: |
          JSON=$(cat ./badges_shields.json)
          echo "matrix=${JSON//'%'/'%25'}" >> $GITHUB_OUTPUT
    
  
  run_tests:
      needs: get_test_scope
      runs-on: ubuntu-latest
      steps:
        - name: print from next job
          run: echo ${{ needs.get_test_scope.outputs.matrix }}
