# Build and publish the package on TestPyPI

name: Test Publish
run-name: Test Publish on TestPyPI

on:
  push:
  pull_request:
  release:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: bash -l {0}


jobs:

  get_package_metadata:
    name: Get Package Metadata
    outputs:
      package_name: ${{ fromJson(steps.get_metadata.outputs.json).package.name }}
      python_versions: ${{ toJson(fromJson(steps.get_metadata.outputs.json).package.python_versions) }}
      operating_systems: ${{ toJson(fromJson(steps.get_metadata.outputs.json).package.operating_systems) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Metadata
        id: get_metadata
        uses: ./.github/actions/get-metadata
        with:
          json_filepath: ./metadata/main.json

      - name: Print Extracted Data
        id: extract
        run: |
          echo "Package Name: ${{ fromJson(steps.get_metadata.outputs.json).package.name }}" 
          echo "Python Versions: '${{ toJson(fromJson(steps.get_metadata.outputs.json).package.python_versions) }}'" 
          echo "OS: '${{ toJson(fromJson(steps.get_metadata.outputs.json).package.operating_systems) }}'"


  build:
    name: Build and Publish
    needs: get_package_metadata
    runs-on: ubuntu-latest
    environment:
      name: testpypi
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print System Info
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install build
        run: python -m pip install build --user

      - name: Build sdist and wheel
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/