
name: Test
run-name: Test from ${{ github.head_ref || github.ref }}

on:
  workflow_dispatch:
  push:

jobs:

  get-metadata:
    uses: ./.github/workflows/repo_get-metadata.yaml

  print:
    if: always()
    needs: get-metadata
    runs-on: ubuntu-latest
    steps:

      - name: 'print'
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.ref }}
          echo "${{fromJSON(needs.get-metadata.outputs.json)}}"
