name: CI NEW
run-name: CI NEW
on: [workflow_dispatch, push]
jobs:
  get_test_scope:
    name: Get Metadata from Workflow
    uses: ./.github/workflows/get_metadata.yaml
  
  Test-Output:
      name: Print Metadata Values
      needs: get_test_scope
      runs-on: ubuntu-latest
      steps:
        - name: Complete JSON File
          run: echo ${{ needs.get_test_scope.outputs.json_file }}
        - name: JSON File fromJson
          run: echo ${{ fromJson(needs.get_test_scope.outputs.json_file) }}
        - name: Package Name
          run: echo ${{ needs.get_test_scope.outputs.package_name }}
            
            
  build-and-install:
    needs: get_test_scope
    name: Build (${{ matrix.os }}, Py ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10"] # ${{ fromJson(needs.get_test_scope.outputs.python_versions) }}
    env:
      PACKAGE: "template_package"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Additional build info
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install dependencies
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: deps/env_user.yaml
          cache-env: true
          extra-specs: |
            python=${{ matrix.python-version }}

      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install . --no-deps
          pip list
