name: TT2
run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch, push]
jobs:
  Run-My-Script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Script
        shell: bash -l {0}
        run: |
          echo ::set-output name=matrix::$(python "dev/utils.py")
          
         # echo ::set-output name=python-versions::${{ steps.matrix.outputs.python_versions }}
         # echo "Python versions: ${{ steps.matrix.outputs.python-versions }}"
