# Test the build of documentation with Sphinx

name: Docs Build Test
run-name: Docs Build Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


jobs:

  build_docs:

    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print System Info
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install Docs Dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: requirements/dev/doc.yaml

      - name: Print Environment
        shell: bash -el {0}
        run: micromamba list

      - name: Install Package
        run: python -m pip install .
        shell: micromamba-shell {0}

      - name: Print Installed Packages
        run: python -m pip list
        shell: micromamba-shell {0}

      - name: Build with Sphinx
        if: always()
        shell: micromamba-shell {0}
        run: |
          cd docs
          make clean
          SPHINXOPTS="-W -T --keep-going" make html

      - name: 'Upload built website as artifact'
        uses: actions/upload-artifact@v3
        with:
          path: docs/_build/*
          name: Built Website
