# Test the build of the Python package

name: Test Build
run-name: Test Build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'


jobs:

  get_package_metadata:
    name: Get package metadata
    outputs:
      package_name: ${{ fromJson(steps.get_metadata.outputs.json).package.name }}
      python_versions: ${{ toJson(fromJson(steps.get_metadata.outputs.json).package.python_versions) }}
      operating_systems: ${{ toJson(fromJson(steps.get_metadata.outputs.json).package.operating_systems) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Metadata
        id: get_metadata
        uses: ./.github/actions/get-metadata
        with:
          json_filepath: ./metadata/main.json

      - name: Print Extracted Data
        id: extract
        run: |
          echo "Package Name: ${{ fromJson(steps.get_metadata.outputs.json).package.name }}" 
          echo "Python Versions: ${{ toJson(fromJson(steps.get_metadata.outputs.json).package.python_versions) }}" 
          echo "OS: ${{ toJson(fromJson(steps.get_metadata.outputs.json).package.operating_systems) }}"


  build:
    name: Build (Python ${{ matrix.python-version }}, ${{ matrix.os }})
    needs: get_package_metadata
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.get_package_metadata.outputs.operating_systems) }}
        python-version: ${{ fromJson(needs.get_package_metadata.outputs.python_versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print System Info
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Install Package
        run: python -m pip install .

      - name: Print Installed Packages
        run: python -m pip list


      - name: Install pipreqs
        run: python -m pip install --upgrade pipreqs

      - name: Check Dependencies
        run: |
          echo "PYTHONWARNINGS=error" >> $GITHUB_OUTPUT
          python -W error -m pipreqs --entry-point pipreqs --debug --print ${{ needs.get_package_metadata.outputs.package_name }}


      - name: Import Package
        shell: python
        run: |
          import ${{ needs.get_package_metadata.outputs.package_name }}
          print(${{ needs.get_package_metadata.outputs.package_name }}.__version__)