name: test

on:
  workflow_dispatch:

jobs:

  tag:
    name: 'Create tag'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - shell: python
        run: |
          import json
          import os

          x = json.loads("""${{ toJSON(github) }}""", strict=False)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'json={json.dumps(x, )}', file=fh)
          with open("github_workload_dispatch.json", "w") as f:
            json.dump(x, f, indent=4)

      - name: Tag and push current repo code
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name ${{ github.actor }}
          git tag -a "v0.0.5" -m "Release version 0.0.5"
          git push origin "v0.0.5"